### ISSUE TITLE
crashes almost instantly

### ISSUE THREAD

**Issue by colourfullyy** [RoanH/KeysPerSecond#39]
hi, when I try to start the .jar application from command line using java -jar KeysPerSecond-v8.4.jar, it opens without any gui and outputs this in the cmd and crashes: 
Ctrl + P: Causes the program to reset and print the average and maximum value
Ctrl + U: Terminates the program
Ctrl + I: Causes the program to reset and print the key press statistics
Ctrl + Y: Hides/shows the GUI
Ctrl + T: Pauses/resumes the counter
Ctrl + R: Reloads the configuration
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.Integer com.github.kwhat.jnativehook.GlobalScreen.getAutoRepeatRate()'
	at com.github.kwhat.jnativehook.GlobalScreen.getAutoRepeatRate(Native Method)
	at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:96)
	at me.roan.kps.Main.setupNativeHook(Main.java:350)
	at me.roan.kps.Main.main(Main.java:240)
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class com.github.kwhat.jnativehook.GlobalScreen
	at me.roan.kps.Main$1.run(Main.java:232)

I'm not at all familiar with java so I would appreciate help

**Comment by RoanH** [comment]
Interesting issue, I would only expect such an exception when you are not running on a supported system. Which operating system and architecture are you running on?

**Comment by colourfullyy** [comment]
oh yes, forgot to mention that, I'm on an m1 mac running big sur 11.5.2

**Comment by RoanH** [comment]
Ah, yeah unfortunately the library I am currently using to handle key input on Mac only supports 10.5 - 10.12. There is a [feature request issue](https://github.com/kwhat/jnativehook/issues/326) for M1 support, but it doesn't look like it will happen anytime soon. I myself do not own any Apple devices at all, so there's not much I can do since I cannot test anything. So for now waiting for the feature request I linked is the best I can do. There are technically some other things I could do but with a lack of ability to test and time I don't want to make any promises I can't keep.

**Comment by kwhat** [comment]
@RoanH M1 is now added as a target, I have no way of testing it so someone will need to check to see if it works.

@colourfullyy as for the original error, it is cased by not loading the appropriate JNI binary.  I have no idea what KeysPerSecond-v8.4.jar is, but the jnativehook jar should load the binaries for you at runtime.  Does this KeysPerSecond-v8.4.jar jar come with this libraries jar file?  It sounds like you may just have a class path issue.  

`java -classpath c:\Path\To\JNativeHook.jar -jar KeysPerSecond-v8.4.jar` will probably get things running.

**Comment by colourfullyy** [comment]
Hi, I tried the m1 jar and it works flawlessly with a arm jdk.

**Comment by RoanH** [comment]
That's great news! @kwhat seems like M1 support works as intended, thanks again.

As for overlaying applications running in exclusive full screen mode, this is tracked in #28. But this is not something I foresee being implemented in the near future. M1 support will be part of the next release (v8.5) and you can use the M1 jar in the meantime.

**Comment by kwhat** [comment]
Awesome, thanks for testing.
